language: java
addons:
  sonarcloud:
    organization: "abdotalaat" # the key of the org you chose at step #3
    token:
      secure: "$SONAR_TOKEN" # encrypted value of your token

before_script: cd project

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=abdotalaat_CI-CD-with-Dockers-and-Jenkins